language: ruby
rvm:
- 2.0.0
- 2.1.0
gemfile:
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
before_install:
- gem install bundler -v '= 1.5.1'
matrix:
  include:
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.0.x
      env: UPDATE_RESOLVER=true
notifications:
  hipchat:
    rooms:
      secure: godUSQsUQ3WSNt4ec2DYTRXvJzzjgUPcfrQfDVS5lI25eH2zMSHkPreDYTRreoE8Ce3vACkw4aFR5KuP79wBNGptBX48XvsyG55UMvUVfQnfNY5a/DXaMLfnkeoGXCDKoH/JjEQWjVaizGhYVKLjbhEF6iPECxkc9qRiqMJ8H38=
