language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - UPDATE_RESOLVER=false
  - UPDATE_RESOLVER=true
notifications:
  hipchat:
    rooms:
      secure: godUSQsUQ3WSNt4ec2DYTRXvJzzjgUPcfrQfDVS5lI25eH2zMSHkPreDYTRreoE8Ce3vACkw4aFR5KuP79wBNGptBX48XvsyG55UMvUVfQnfNY5a/DXaMLfnkeoGXCDKoH/JjEQWjVaizGhYVKLjbhEF6iPECxkc9qRiqMJ8H38=
