language: ruby
rvm:
- 2.0.0
- 2.1.0
gemfile:
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
before_install:
- gem install bundler -v '= 1.5.1'
matrix:
  include:
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.0.x
      env: UPDATE_RESOLVER=true
notifications:
  slack:
    secure: Gk6UyzsTeb5Sn4hMjiIzUWdN6V18O0s69by2ZNJLic+vOA5igNdqFOj5CfRPeklJR5D+m43Ngx2kquOYUhyH9D4+UZpHGnXOZkJiIU9dFJoUxEhkECE8KVjMQstqCoz/OGtQHQegHupNX5mVHQZOwL4WgzP66+xevKwbVtotc1U=
